package org.apache.apex.api;

/**
 * An interface for Custom Control Tuples which can be generated by the user
 * Any user generated control tuple must implement this interface
 */
public interface ControlTuple
{
}
