package org.apache.apex.api;

import com.datatorrent.api.ControlSink;
import com.datatorrent.api.DefaultInputPort;
import com.datatorrent.api.Operator;

/**
 * Default abstract implementation for {@link Operator.InputPort} which is capable of processing custom control tuples
 */
public abstract class ControlAwareDefaultInputPort<T> extends DefaultInputPort<T> implements ControlSink<T>
{
  @Override
  public void putControl(Object payload)
  {
    count++;
    processControl(payload);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public boolean propogateControlTuples()
  {
    return true;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void setPropogateControlTuples(boolean propogate)
  {
  }

  /**
   * Process the control tuples
   *
   * @param payload the control tuple payload generated by upstream operator(s)
   */
  public abstract void processControl(Object payload);
}
