package com.datatorrent.stram.tuple;

import java.util.UUID;

import com.esotericsoftware.kryo.serializers.FieldSerializer;
import com.esotericsoftware.kryo.serializers.JavaSerializer;

import com.datatorrent.bufferserver.packet.MessageType;

/**
 * An implementation for @{@link Tuple} which can be generated by the user
 * Acts as the wrapper for the user payload
 */
public class CustomControlTuple extends Tuple
{
  private Object userObject;
  @FieldSerializer.Bind(JavaSerializer.class)
  private UUID id;

  public CustomControlTuple()
  {
    super(MessageType.CUSTOM_CONTROL, 0);
  }

  public CustomControlTuple(Object userObject)
  {
    super(MessageType.CUSTOM_CONTROL, 0);
    this.userObject = userObject;
    id = UUID.randomUUID();
  }

  public Object getUserObject()
  {
    return userObject;
  }

  public UUID getId()
  {
    return id;
  }
}
